### ISSUE TITLE
Allow excepting goals

### ISSUE THREAD

**Issue by ja-he** [ja-he/dayplan#40]
A goal defines expected time spent.
An example of this would be working hours over a workweek.

An exception to a goal excepts certain dates from the expectation.
An example of this would be public holidays or sick leave.

Since the definitions for these groups of dates might get verbose and be repetitive between categories' goals, let's let the goal only name an exception

```yaml
categories:
  name: work
  goal:
    workweek:
      monday: 8
      tuesday: 4
    except: [ 'public-holidays' ]
```

where then we define below

```yaml
date-groups:
  'public-holidays':
    - 2022-12-24..2022-12-26
    - 2022-12-31
```
